import Foundation

/// Flat key→{zh,en} string table, mirroring the shape (if not every exact key) of
/// calorie-app's `constants/translations.js`.
enum Strings {
    static let table: [String: [AppLanguage: String]] = [
        // MARK: Common
        "common.save": [.zh: "儲存", .en: "Save"],
        "common.cancel": [.zh: "取消", .en: "Cancel"],
        "common.done": [.zh: "完成", .en: "Done"],
        "common.delete": [.zh: "刪除", .en: "Delete"],
        "common.edit": [.zh: "編輯", .en: "Edit"],
        "common.confirm": [.zh: "確認", .en: "Confirm"],
        "common.loading": [.zh: "載入中…", .en: "Loading…"],
        "common.retry": [.zh: "重試", .en: "Retry"],
        "common.ok": [.zh: "好", .en: "OK"],
        "common.back": [.zh: "返回", .en: "Back"],
        "common.next": [.zh: "下一步", .en: "Next"],
        "common.skip": [.zh: "略過", .en: "Skip"],
        "common.today": [.zh: "今天", .en: "Today"],
        "common.kcal": [.zh: "大卡", .en: "kcal"],

        // MARK: Auth
        "auth.loginTitle": [.zh: "歡迎回來", .en: "Welcome Back"],
        "auth.registerTitle": [.zh: "建立帳號", .en: "Create Account"],
        "auth.email": [.zh: "電子郵件", .en: "Email"],
        "auth.password": [.zh: "密碼", .en: "Password"],
        "auth.username": [.zh: "使用者名稱", .en: "Username"],
        "auth.firstName": [.zh: "名字", .en: "First Name"],
        "auth.lastName": [.zh: "姓氏", .en: "Last Name"],
        "auth.loginButton": [.zh: "登入", .en: "Log In"],
        "auth.registerButton": [.zh: "註冊", .en: "Sign Up"],
        "auth.forgotPassword": [.zh: "忘記密碼？", .en: "Forgot password?"],
        "auth.noAccount": [.zh: "還沒有帳號？", .en: "Don't have an account?"],
        "auth.haveAccount": [.zh: "已經有帳號？", .en: "Already have an account?"],
        "auth.continueWithGoogle": [.zh: "使用 Google 繼續", .en: "Continue with Google"],
        "auth.or": [.zh: "或", .en: "or"],
        "auth.forgotAlert": [.zh: "此功能尚未提供，請聯繫客服協助重設密碼。", .en: "This feature isn't available yet — please contact support to reset your password."],

        // MARK: Onboarding
        "onboarding.genderTitle": [.zh: "你的性別是？", .en: "What's your gender?"],
        "onboarding.male": [.zh: "男性", .en: "Male"],
        "onboarding.female": [.zh: "女性", .en: "Female"],
        "onboarding.ageTitle": [.zh: "你的年齡是？", .en: "How old are you?"],
        "onboarding.heightTitle": [.zh: "你的身高是？", .en: "What's your height?"],
        "onboarding.weightTitle": [.zh: "你目前的體重是？", .en: "What's your current weight?"],
        "onboarding.targetWeightTitle": [.zh: "你的目標體重是？", .en: "What's your target weight?"],
        "onboarding.durationTitle": [.zh: "你想花多久時間達成？", .en: "How long do you want to take?"],
        "onboarding.activityTitle": [.zh: "你的日常活動量是？", .en: "What's your activity level?"],
        "onboarding.finish": [.zh: "完成設定", .en: "Finish Setup"],
        "onboarding.buildingPlan": [.zh: "正在為你打造專屬計畫…", .en: "Building your personalized plan…"],
        "onboarding.months": [.zh: "個月", .en: "months"],
        "onboarding.custom": [.zh: "自訂", .en: "Custom"],

        "activity.sedentary": [.zh: "久坐", .en: "Sedentary"],
        "activity.sedentary.desc": [.zh: "很少或沒有運動", .en: "Little or no exercise"],
        "activity.lightly": [.zh: "輕度活動", .en: "Lightly Active"],
        "activity.lightly.desc": [.zh: "每週運動 1–3 天", .en: "Exercise 1–3 days/week"],
        "activity.moderately": [.zh: "中度活動", .en: "Moderately Active"],
        "activity.moderately.desc": [.zh: "每週運動 3–5 天", .en: "Exercise 3–5 days/week"],
        "activity.very": [.zh: "高度活動", .en: "Very Active"],
        "activity.very.desc": [.zh: "每週運動 6–7 天", .en: "Exercise 6–7 days/week"],
        "activity.extra": [.zh: "極高強度", .en: "Extra Active"],
        "activity.extra.desc": [.zh: "高強度訓練或體力勞動工作", .en: "Hard training or physical job"],

        // MARK: Tabs
        "tab.diary": [.zh: "日誌", .en: "Diary"],
        "tab.progress": [.zh: "進度", .en: "Progress"],
        "tab.coach": [.zh: "教練", .en: "Coach"],
        "tab.profile": [.zh: "我的", .en: "Profile"],
        "tab.lookup": [.zh: "食品庫", .en: "Foods"],

        // MARK: Diary
        "diary.eaten": [.zh: "已攝取", .en: "Eaten"],
        "diary.left": [.zh: "剩餘", .en: "Left"],
        "diary.goal": [.zh: "目標", .en: "Goal"],
        "diary.protein": [.zh: "蛋白質", .en: "Protein"],
        "diary.carbs": [.zh: "碳水", .en: "Carbs"],
        "diary.fat": [.zh: "脂肪", .en: "Fat"],
        "diary.breakfast": [.zh: "早餐", .en: "Breakfast"],
        "diary.lunch": [.zh: "午餐", .en: "Lunch"],
        "diary.dinner": [.zh: "晚餐", .en: "Dinner"],
        "diary.snacks": [.zh: "點心", .en: "Snacks"],
        "diary.addFood": [.zh: "新增食物", .en: "Add Food"],
        "diary.scanFood": [.zh: "拍照辨識", .en: "Scan Food"],
        "diary.uploadImage": [.zh: "上傳照片", .en: "Upload Photo"],
        "diary.adjustGoal": [.zh: "調整目標", .en: "Adjust Goal"],
        "diary.streak": [.zh: "連續天數", .en: "Day Streak"],
        "diary.noMeals": [.zh: "尚未記錄", .en: "Nothing logged yet"],
        "diary.calendar": [.zh: "月曆", .en: "Calendar"],

        // MARK: Camera
        "camera.title": [.zh: "拍照辨識", .en: "Scan Food"],
        "camera.takePhoto": [.zh: "拍照", .en: "Take Photo"],
        "camera.choosePhoto": [.zh: "從相簿選擇", .en: "Choose from Library"],
        "camera.retake": [.zh: "重新拍攝", .en: "Retake"],
        "camera.describe": [.zh: "補充說明（選填）", .en: "Add a description (optional)"],
        "camera.analyze": [.zh: "確認分析", .en: "Analyze"],
        "camera.analyzing": [.zh: "分析中…", .en: "Analyzing…"],
        "camera.remaining": [.zh: "今日剩餘熱量", .en: "Remaining today"],
        "camera.save": [.zh: "儲存紀錄", .en: "Save to Log"],
        "camera.saved": [.zh: "已儲存！", .en: "Saved!"],
        "camera.failedTitle": [.zh: "辨識失敗", .en: "Analysis Failed"],

        // MARK: Errors (see LocalizationStore.message(for:))
        "error.network": [.zh: "無法連線到伺服器，請檢查網路後再試一次", .en: "Can't reach the server. Check your connection and try again."],
        "error.timeout": [.zh: "連線逾時，請再試一次", .en: "The request timed out. Please try again."],
        "error.server": [.zh: "伺服器暫時無法回應，請稍後再試", .en: "The server isn't responding right now. Please try again later."],
        "error.generic": [.zh: "發生錯誤，請再試一次", .en: "Something went wrong. Please try again."],
        "error.unauthorized": [.zh: "登入已過期，請重新登入", .en: "Your session expired. Please sign in again."],
        "error.wrongCredentials": [.zh: "Email 或密碼錯誤", .en: "Incorrect email or password."],
        "error.googleFailed": [.zh: "Google 登入失敗，請再試一次", .en: "Google sign-in failed. Please try again."],
        "error.emailTaken": [.zh: "這個 Email 已經註冊過了", .en: "That email is already registered."],
        "error.usernameTaken": [.zh: "這個使用者名稱已經有人使用", .en: "That username is already taken."],
        "error.invalidRegister": [.zh: "請填寫有效的 Email、使用者名稱，密碼至少 4 碼", .en: "Enter a valid email and username, and a password of at least 4 characters."],
        "error.noFood": [.zh: "照片裡找不到食物，換個角度再拍一次", .en: "No food found in the photo. Try another angle."],
        "error.rateLimited": [.zh: "嘗試次數太多，請稍後再試", .en: "Too many attempts. Please try again later."],
        "profile.languageHint": [.zh: "AI 辨識的食物名稱也會跟著切換。相機權限等系統視窗在下次開啟 App 時生效。", .en: "AI food names follow this setting too. System dialogs (like camera permission) switch the next time you open the app."],

        // MARK: Food lookup (Open Food Facts)
        "diary.searchPackaged": [.zh: "條碼 / 搜尋包裝食品", .en: "Barcode / Packaged Foods"],
        "lookup.title": [.zh: "食品庫", .en: "Food Database"],
        "lookup.searchPrompt": [.zh: "搜尋包裝食品（英文效果最好）", .en: "Search packaged foods"],
        "lookup.scan": [.zh: "掃描條碼", .en: "Scan Barcode"],
        "lookup.scanHint": [.zh: "對準包裝上的條碼，自動查詢營養標示", .en: "Point at a barcode to look up its nutrition label"],
        "lookup.poweredBy": [.zh: "資料來源：Open Food Facts 開放食品資料庫", .en: "Data from Open Food Facts"],
        "lookup.favorites": [.zh: "我的最愛", .en: "Favorites"],
        "lookup.recent": [.zh: "最近查看", .en: "Recently Viewed"],
        "lookup.emptyTitle": [.zh: "還沒有查過任何食品", .en: "No foods yet"],
        "lookup.emptyHint": [.zh: "掃描條碼或在上方搜尋，查過的食品會存在手機裡，離線也看得到", .en: "Scan or search — viewed foods are saved on this device and work offline"],
        "lookup.noResults": [.zh: "找不到符合的食品", .en: "No matching foods"],
        "lookup.noResultsHint": [.zh: "試試英文名稱或品牌，例如 oreo、coca cola", .en: "Try a brand or English name, e.g. oreo"],
        "lookup.results": [.zh: "搜尋結果", .en: "Results"],
        "lookup.per100g": [.zh: "每 100 公克", .en: "Per 100 g"],
        "lookup.portion": [.zh: "份量", .en: "Portion"],
        "lookup.serving": [.zh: "一份", .en: "1 serving"],
        "lookup.grams": [.zh: "公克", .en: "g"],
        "lookup.sugar": [.zh: "糖", .en: "Sugar"],
        "lookup.fiber": [.zh: "膳食纖維", .en: "Fiber"],
        "lookup.sodium": [.zh: "鈉", .en: "Sodium"],
        "lookup.mealType": [.zh: "加入哪一餐", .en: "Add to meal"],
        "lookup.addToLog": [.zh: "加入今日紀錄", .en: "Add to Log"],
        "lookup.added": [.zh: "已加入！", .en: "Added!"],
        "lookup.cachedOffline": [.zh: "目前離線，顯示手機裡儲存的資料", .en: "Offline — showing the copy saved on this device"],
        "lookup.manualEntry": [.zh: "手動輸入條碼", .en: "Enter barcode manually"],
        "lookup.manualPlaceholder": [.zh: "8 或 13 碼數字", .en: "8 or 13 digits"],
        "lookup.lookUp": [.zh: "查詢", .en: "Look Up"],
        "lookup.tryExample": [.zh: "試試範例：可口可樂 330ml", .en: "Try an example: Coca-Cola 330ml"],
        "lookup.scannerUnavailable": [.zh: "這台裝置不支援相機掃描（例如模擬器），請手動輸入條碼", .en: "Camera scanning isn't available on this device (e.g. Simulator) — enter the barcode instead"],
        "lookup.searching": [.zh: "查詢中…", .en: "Searching…"],
        "lookup.error.invalidBarcode": [.zh: "條碼格式不正確，應為 8、12 或 13 碼數字", .en: "That isn't a valid barcode (8, 12 or 13 digits)"],
        "lookup.error.notFound": [.zh: "資料庫裡還沒有這個商品", .en: "This product isn't in the database yet"],
        "lookup.error.noNutrition": [.zh: "找到商品了，但它沒有熱量資料", .en: "Found it, but it has no calorie data"],
        "lookup.error.rateLimited": [.zh: "查詢太頻繁，請稍等一分鐘再試", .en: "Too many searches — wait a minute and try again"],
        "lookup.error.offline": [.zh: "無法連線，請檢查網路", .en: "You're offline — check your connection"],
        "lookup.error.server": [.zh: "Open Food Facts 暫時無法回應，請稍後再試", .en: "Open Food Facts isn't responding — try again later"],
        "lookup.error.decoding": [.zh: "資料格式無法解析", .en: "Couldn't read the response"],

        // MARK: Coach
        "coach.title": [.zh: "AI 教練即將推出", .en: "AI Coach Coming Soon"],
        "coach.subtitle": [.zh: "我們正在打造你的專屬營養教練，敬請期待！", .en: "We're building your personal nutrition coach. Stay tuned!"],

        // MARK: Progress
        "progress.overall": [.zh: "整體進度", .en: "Overall Progress"],
        "progress.daysTracked": [.zh: "追蹤天數", .en: "Days Tracked"],
        "progress.currentStreak": [.zh: "目前連續天數", .en: "Current Streak"],
        "progress.avgIntake": [.zh: "平均攝取", .en: "Avg. Intake"],
        "progress.adherence": [.zh: "達標率", .en: "Adherence Rate"],
        "progress.weightChange": [.zh: "體重變化", .en: "Weight Change"],
        "progress.todaySummary": [.zh: "今日總覽", .en: "Today's Summary"],
        "progress.sevenDayTrend": [.zh: "7 天熱量趨勢", .en: "7-Day Trend"],
        "progress.average": [.zh: "平均", .en: "Average"],
        "progress.total": [.zh: "總計", .en: "Total"],
        "progress.empty": [.zh: "開始記錄飲食以查看你的進度", .en: "Start logging meals to see your progress"],

        // MARK: Profile
        "profile.editProfile": [.zh: "編輯個人資料", .en: "Edit Profile"],
        "profile.bmi": [.zh: "BMI", .en: "BMI"],
        "profile.tdee": [.zh: "TDEE", .en: "TDEE"],
        "profile.bmr": [.zh: "BMR", .en: "BMR"],
        "profile.personalInfo": [.zh: "個人資訊", .en: "Personal Info"],
        "profile.gender": [.zh: "性別", .en: "Gender"],
        "profile.age": [.zh: "年齡", .en: "Age"],
        "profile.height": [.zh: "身高", .en: "Height"],
        "profile.weight": [.zh: "體重", .en: "Weight"],
        "profile.activity": [.zh: "活動量", .en: "Activity Level"],
        "profile.accountSync": [.zh: "帳號與同步", .en: "Account & Sync"],
        "profile.loggedIn": [.zh: "已登入・自動同步", .en: "Logged in · syncing"],
        "profile.logout": [.zh: "登出", .en: "Log Out"],
        "profile.loginPrompt": [.zh: "登入以同步你的資料", .en: "Log in to sync your data"],
        "profile.appSettings": [.zh: "App 設定", .en: "App Settings"],
        "profile.language": [.zh: "語言", .en: "Language"],
        "profile.appearance": [.zh: "外觀", .en: "Appearance"],
        "profile.notifications": [.zh: "通知", .en: "Notifications"],
        "profile.units": [.zh: "單位", .en: "Units"],
        "profile.privacy": [.zh: "隱私權", .en: "Privacy"],
        "profile.about": [.zh: "關於", .en: "About"],
        "profile.comingSoon": [.zh: "此功能尚未提供", .en: "This isn't available yet"],
        "profile.sendFeedback": [.zh: "傳送意見回饋", .en: "Send Feedback"],
        "profile.feedbackPlaceholder": [.zh: "告訴我們你的想法…", .en: "Tell us what you think…"],
        "profile.feedbackSent": [.zh: "感謝你的回饋！", .en: "Thanks for your feedback!"],
        "profile.version": [.zh: "版本 1.0.0", .en: "Version 1.0.0"],
        "profile.bmrFormula": [.zh: "BMR 公式（Harris-Benedict）", .en: "BMR Formula (Harris-Benedict)"],
        "profile.tdeeFormula": [.zh: "TDEE = BMR × 活動係數", .en: "TDEE = BMR × Activity Factor"],

        "bmi.underweight": [.zh: "過輕", .en: "Underweight"],
        "bmi.normal": [.zh: "正常", .en: "Normal"],
        "bmi.overweight": [.zh: "過重", .en: "Overweight"],
        "bmi.obese": [.zh: "肥胖", .en: "Obese"],

        "goal.bulk": [.zh: "增肌", .en: "Bulk"],
        "goal.cut": [.zh: "減脂", .en: "Cut"],
        "goal.maintain": [.zh: "維持", .en: "Maintain"],
    ]
}
